spring:
  application:
    name: EurekaRegistry

server:
  port: 8761

eureka:
  instance:
    lease-renewal-interval-in-seconds: 0

  client:
    fetch-registry: false
    register-with-eureka: false